// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // `node dist/prisma/seed.js`, et non `ts-node prisma/seed.ts` : le client
    // généré par Prisma 7 est du TypeScript dont les imports portent des
    // suffixes `.js`, que `ts-node` en CommonJS ne sait pas ramener sur les
    // `.ts` voisins — « Cannot find module './internal/class.js' ». Le seul
    // chemin qui charge ce client est celui que l'application emprunte
    // elle-même : compiler d'abord. `nest build` émet déjà `dist/prisma/`.
    seed: "node dist/prisma/seed.js",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
